language: minimal

services:
  - docker

if: branch = f-assignment

jobs:
  include:
    - stage: build docker image
      script:
        - docker build -t ${DOCKER_USERNAME}/${DOCKER_REPO}:latest .
        - docker tag ${DOCKER_USERNAME}/${DOCKER_REPO}:latest ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_COMMIT}
        - docker tag ${DOCKER_USERNAME}/${DOCKER_REPO}:latest ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_BRANCH}__${TRAVIS_COMMIT}__${TRAVIS_JOB_NUMBER} 
        - docker tag ${DOCKER_USERNAME}/${DOCKER_REPO}:latest ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_BRANCH}
        - echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_COMMIT}
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_BRANCH}__${TRAVIS_COMMIT}__${TRAVIS_JOB_NUMBER}
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:${TRAVIS_BRANCH}
        - docker push ${DOCKER_USERNAME}/${DOCKER_REPO}:latest
    - stage: smoke test
      script:
        - echo "placeholder for smoke test"
    - stage: deploy
      script:
        - echo "placeholder for deploy script"
