language: java

services:
  - docker

script:
  - docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_COMMIT -t $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_BRANCH#$TRAVIS_COMMIT#$TRAVIS_JOB_NUMBER -t $DOCKER_USERNAME/$DOCKER_REPO:latest .

deploy:
  provider: script
  script:
    - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_COMMIT
    - docker push $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_BRANCH#$TRAVIS_COMMIT#$TRAVIS_JOB_NUMBE
    - docker push $DOCKER_USERNAME/$DOCKER_REPO:latest
  on:
    branch: f-assignment
